import urllib.request
import json

def api_call(port, path, payload):
    req = urllib.request.Request(
        f"http://127.0.0.1:{port}{path}",
        data=json.dumps(payload).encode('utf-8'),
        headers={'Content-Type': 'application/json'}
    )
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read().decode('utf-8'))

print("Starting test workflow for 'make a bottle'...")
request_text = "make a bottle"

# 1. Supervisor
print("1. Supervisor")
sup_res = api_call(8003, "/supervisor/evaluate", {"instruction": request_text})
print(sup_res)

# 2. Planner
print("2. Planner")
context = {
    "parameter_answers": {},
    "completed_steps": [],
    "remaining_steps": [],
    "errors": [],
    "pending_questions": []
}

planner_res = api_call(8004, "/planner", {"request": request_text, "context": context})
print("Planner Initial Response:", planner_res)

if planner_res.get("status") in ["needs_info", "needs_parameters"]:
    for q in planner_res.get("questions", []):
        context["parameter_answers"][q["parameter_id"]] = "10 cm" # use parameter_id
    
    print("Answering questions and calling planner again...")
    planner_res = api_call(8004, "/planner", {"request": request_text, "context": context})
    print("Planner Second Response:", planner_res)

steps = planner_res.get("steps", [])
if not steps:
    print("No steps generated by planner!")
    exit(1)

# 3. Code Generator
print("3. Code Generator")
runned_codes = []
for step in steps:
    print(f"Generating code for step: {step}")
    payload = {
        "step": step.get("description", step.get("title", str(step))),
        "previous_code": "\n".join(runned_codes)
    }
    cg_res = api_call(8001, "/generate", payload)
    print("Response:", cg_res)
    if "code" in cg_res:
        runned_codes.extend(cg_res["code"])

print("FINAL CODE:")
print("\n".join(runned_codes))
